### ISSUE TITLE
feat(world-chain-builder): Enable PBH support for 4337 `UserOps`

### ISSUE THREAD

**Issue by 0xKitsune** [worldcoin/world-chain#67]
Currently, the World Chain Builder enables priority blockspace for humans via the [PBH Tx envelope](https://github.com/worldcoin/world-chain/blob/main/world-chain-builder/docs/pbh_tx_lifecycle.md#creating-a-pbh-transaction), allowing users to provide a World ID proof, setting the signal of the proof as the transaction hash.  

While this mechanism enables any user with a valid World ID to create a priority transaction, this requires that a user has Eth in their account to pay for gas.  PBH validation should also be extended to support 4337 `UserOps`, allowing a third party to submit a single `UserOp` with top of block priority on behalf of a World ID user.

## 4337 PBH Validation

A valid PBH `UserOp` needs to adhere to the following:
- The `signal` of the proof must be the hash of [all 4337 `UserOp` fields concatenated together](https://www.erc4337.io/docs/understanding-ERC-4337/user-operation)
- The `to` address of the transaction must be the Entrypoint contract
- The `UserOp` signature should be validated to ensure the proper sender and nonce is specified.
- The transaction calldata can only specify a single `UserOp`. Transactions that bundle multiple `UserOps` should not be provided priority blockspace

Tasks
- [x] #72

**Comment by 0xOsiris** [comment]
Closing as complete ✅
